---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: wordpress-server
  #remote_user: root
  remote_user: ubuntu
  sudo: yes

  roles:
#    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
