---
 - name: Install nginx on Amazon Linux 
   yum: name=nginx state=present
   when: ansible_distribution == 'Amazon'

 - name: Install Nginx on Ubuntu
   apt: pkg=nginx state=present update_cache=yes
   when: ansible_distribution == 'Ubuntu'
 
 - name: Copy nginx configuration
   template: src={{ nginx_conf }} dest=/etc/nginx/conf.d/{{ server_hostname }}.conf
   notify: restart nginx
   when: ansible_distribution == 'Amazon'

 - name: Copy nginx configuration 
   template: src={{ nginx_conf }} dest=/etc/nginx/sites-enabled/{{ server_hostname }}
   notify: restart nginx
   when: ansible_distribution == 'Ubuntu'
